In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

Na skupu <code>24-bank.csv</code> izvršiti sledece promene:

a) Učitati skup podataka.

In [2]:
data = pd.read_csv('datasets/24-bank.csv')

b) Ispisati prvih nekoliko instanci i dimenzije skupa podataka.

In [3]:
data.head()

,STAROST,POSAO,BRACNO_STANJE,OBRAZOVANJE,SREDNJE_GOD_STANJE_EUR,STAMBENI_KREDIT,LICNI_KREDIT,KONTAKT,DUZINA_RAZGOVORA_SEC,BROJ_RAZGOVORA,OROCENA_STEDNJA
0,30,nezaposlen,u_braku,osnevne,1787,ne,ne,mobilni,79,1,ne
1,33,usluge,u_braku,srednje,4789,da,da,mobilni,220,1,ne
2,35,rukovodstvo,samac,visoko,1350,da,ne,mobilni,185,1,ne
3,30,rukovodstvo,u_braku,visoko,1476,da,da,nepoznato,199,4,ne
4,59,manuelni_poslovi,u_braku,srednje,0,da,ne,nepoznato,226,1,ne

In [4]:
data.shape

(4521, 11)

c) Prikazati deskriptivne statistike svih atributa.

In [5]:
data.describe()

,STAROST,SREDNJE_GOD_STANJE_EUR,DUZINA_RAZGOVORA_SEC,BROJ_RAZGOVORA
count,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,263.961292,2.793630
std,10.576211,3009.638142,259.856633,3.109807
min,19.000000,-3313.000000,4.000000,1.000000
25%,33.000000,69.000000,104.000000,1.000000
50%,39.000000,444.000000,185.000000,2.000000
75%,49.000000,1480.000000,329.000000,3.000000
max,87.000000,71188.000000,3025.000000,50.000000

d) Eliminisati instance koje imaju negativnu vrednost atributa <code>SREDNJE_GOD_STANJE_EUR</code>.

In [6]:
data.replace(data['SREDNJE_GOD_STANJE_EUR'] < 0, np.nan, inplace=True)

***II način:***

In [7]:
data['SREDNJE_GOD_STANJE_EUR'] = data['SREDNJE_GOD_STANJE_EUR'].apply(lambda x : np.nan if x < 0 else x)

In [8]:
data.isna().any()

STAROST                   False
POSAO                     False
BRACNO_STANJE             False
OBRAZOVANJE               False
SREDNJE_GOD_STANJE_EUR     True
STAMBENI_KREDIT           False
LICNI_KREDIT              False
KONTAKT                   False
DUZINA_RAZGOVORA_SEC      False
BROJ_RAZGOVORA            False
OROCENA_STEDNJA           False
dtype: bool

In [9]:
data.dropna(inplace=True)           #ne moramo navoditi subset=['SREDNJE_GOD_STANJE_EUR'] zato sto 
data.shape                          #je to ionako jedina kolona koja ima nedostajuce vrednosti

(4155, 11)

Uticaj ove transformacije na deskriptivne statistike:

In [10]:
data.describe()

,STAROST,SREDNJE_GOD_STANJE_EUR,DUZINA_RAZGOVORA_SEC,BROJ_RAZGOVORA
count,4155.000000,4155.000000,4155.000000,4155.000000
mean,41.297232,1577.000963,263.861372,2.802888
std,10.694177,3090.416228,260.473877,3.114009
min,19.000000,0.000000,4.000000,1.000000
25%,33.000000,141.500000,104.000000,1.000000
50%,39.000000,542.000000,186.000000,2.000000
75%,49.000000,1637.000000,328.000000,3.000000
max,87.000000,71188.000000,3025.000000,50.000000

e) Vrednosti atributa <code>STAROST</code> podeliti u 5 kategorija jednake širine.

In [11]:
data['STAROST'] = pd.cut(data['STAROST'], bins=5, labels=[1, 2, 3, 4, 5])

In [12]:
data['STAROST'].unique()

[1, 2, 3, 4, 5]
Categories (5, int64): [1 < 2 < 3 < 4 < 5]

f) Promeniti kategorije atributa <code>BRACNO_STANJE</code> u <code>u_braku</code> i <code>nije_u_braku</code>.

In [13]:
data['BRACNO_STANJE'].unique()

array(['u_braku', 'samac', 'razveden(a)'], dtype=object)

In [14]:
data['BRACNO_STANJE'].replace(['samac', 'razveden(a)'], 'nije_u_braku', inplace=True)

In [15]:
data.head()

,STAROST,POSAO,BRACNO_STANJE,OBRAZOVANJE,SREDNJE_GOD_STANJE_EUR,STAMBENI_KREDIT,LICNI_KREDIT,KONTAKT,DUZINA_RAZGOVORA_SEC,BROJ_RAZGOVORA,OROCENA_STEDNJA
0,1,nezaposlen,u_braku,osnevne,1787.0,ne,ne,mobilni,79,1,ne
1,2,usluge,u_braku,srednje,4789.0,da,da,mobilni,220,1,ne
2,2,rukovodstvo,nije_u_braku,visoko,1350.0,da,ne,mobilni,185,1,ne
3,1,rukovodstvo,u_braku,visoko,1476.0,da,da,nepoznato,199,4,ne
4,3,manuelni_poslovi,u_braku,srednje,0.0,da,ne,nepoznato,226,1,ne

g) Izdvojiti samo numericke atribute.

In [16]:
data.dtypes

STAROST                   category
POSAO                       object
BRACNO_STANJE               object
OBRAZOVANJE                 object
SREDNJE_GOD_STANJE_EUR     float64
STAMBENI_KREDIT             object
LICNI_KREDIT                object
KONTAKT                     object
DUZINA_RAZGOVORA_SEC         int64
BROJ_RAZGOVORA               int64
OROCENA_STEDNJA             object
dtype: object

In [17]:
num_attributes = data.dtypes[(data.dtypes == 'int64') | (data.dtypes == 'float64')].index
num_attributes

Index(['SREDNJE_GOD_STANJE_EUR', 'DUZINA_RAZGOVORA_SEC', 'BROJ_RAZGOVORA'], dtype='object')

h) Standardizovati numeričke atribute. Prikazati deskriptivne statistike svih atributa nakon ove transformacije.

In [18]:
scaler = preprocessing.StandardScaler()

In [19]:
scaler.fit(data[num_attributes])    #fit - uci raspodele (izracunava mean i std) svakog od atributa

StandardScaler()

In [20]:
data[num_attributes] = scaler.transform(data[num_attributes])

In [21]:
data.head()

,STAROST,POSAO,BRACNO_STANJE,OBRAZOVANJE,SREDNJE_GOD_STANJE_EUR,STAMBENI_KREDIT,LICNI_KREDIT,KONTAKT,DUZINA_RAZGOVORA_SEC,BROJ_RAZGOVORA,OROCENA_STEDNJA
0,1,nezaposlen,u_braku,osnevne,0.067960,ne,ne,mobilni,-0.709797,-0.579030,ne
1,2,usluge,u_braku,srednje,1.039467,da,da,mobilni,-0.168411,-0.579030,ne
2,2,rukovodstvo,nije_u_braku,visoko,-0.073462,da,ne,mobilni,-0.302798,-0.579030,ne
3,1,rukovodstvo,u_braku,visoko,-0.032686,da,da,nepoznato,-0.249043,0.384474,ne
4,3,manuelni_poslovi,u_braku,srednje,-0.510349,da,ne,nepoznato,-0.145373,-0.579030,ne

Takođe je dostupna bibliotečka podrška i za sledeće tehnike normalizacije:
- Min-max skaliranje - klasa <code>sklearn.preprocessing.MinMaxScaler</code>
- Odsecanje vrednosti - metod <code>pandas.DataFrame.clip</code>
- Logaritamska transformacija - metod <code>pandas.DataFrame.transform('log')</code>